### ISSUE TITLE
Version 1.0.0

### ISSUE THREAD

**Issue by theelderbeever** [OpenRarity/open-rarity#89]
The following is a list of issues to be completed prior to release of `openrarity 1.0.0`.

- [ ] Data Model Refactor #73 
- [ ] Number display_type support #88
- [ ] Semi-Fungible Token support #87
- [ ] Checksum input/output verification #55
